# --- HARDWARE & LOGGING ---
log_dir: 'training/logs/fakeavceleb_pro_gen'
device: 'cuda'
ngpu: 1
pretrained: 'C:/Users/vishu/AI-Synthesized-Voice-Generalization-main/training/logs/fakeavceleb_pro_gen/AudioFakeDetector_2026-05-09-02-27-18/test/LibriSeVoc/ckpt_19.pth'
manualSeed: 1024
lr_scheduler: ~

# --- MI PARAMETERS (TURNING OFF BROKEN MODULE) ---
mi_param:
  mi_turn_on: True   # <--- This stops the NotImplementedError
  mi_loss_weight: 0.1
  mi_mode_measure: 'JSD'
  mi_mode: 'local'

# --- SAM PARAMETERS (KEEPING THIS ON) ---
sam_param:
  rho: 0.05
  use_adaptive_sam: False

# --- MODEL ARCHITECTURE ---
model_name: AudioFakeDetector
backbone_name: rawnet2
encoder_feat_dim: 1024

backbone_config:
  num_classes: 2
  device: 'cuda'
  nb_classes: 2      
  in_channels: 1
  filts: [128, [128, 128], [128, 512], [512, 512]]
  first_conv: 1024   
  gru_node: 1024
  nb_gru_layer: 3
  nb_fc_node: 1024
  nb_samp: 64000
  mode: adjust_channel
  dropout: 0.05

# --- DATASET & PATHS ---
dataset_type: pair-audio
train_dataset: ['train.list']
test_dataset: ['test.list']
train_file: 'C:/Users/vishu/AI-Synthesized-Voice-Generalization-main/train.list'
test_file: 'C:/Users/vishu/AI-Synthesized-Voice-Generalization-main/test.list'
dataset_root: 'C:/Users/vishu/AI-Synthesized-Voice-Generalization-main/datasets/FakeAVCeleb_audio'

# --- OPTIMIZATION (Batch Size 4) ---
train_batchSize: 4  
test_batchSize: 4
workers: 0          
save_ckpt: true
save_feat: true

label_dict:
  real: 0
  fake: 1

optimizer:
  type: adam
  adam:
    lr: 0.00001
    beta1: 0.9
    beta2: 0.999
    eps: 0.00000001
    weight_decay: 0.0005
    amsgrad: false

nEpochs: 7
start_epoch: 0
save_epoch: 1
rec_iter: 100
cuda: true
cudnn: true

loss_func:
  cls_loss: cross_entropy
  spe_loss: cross_entropy
  con_loss: contrastive_regularization
  rec_loss: l1loss
metric_scoring: auc
